services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: untitled
      POSTGRES_USER: untitled
      POSTGRES_PASSWORD: untitled
    ports:
      - "5432:5432"
    volumes:
      - untitled_pg:/var/lib/postgresql/data

volumes:
  untitled_pg: {}
