services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: personalmetrics
      POSTGRES_USER: personalmetrics
      POSTGRES_PASSWORD: personalmetrics
    ports:
      - "5432:5432"
    volumes:
      - personalmetrics_pg:/var/lib/postgresql/data

volumes:
  personalmetrics_pg: {}
